main/urls.py
from django.urls import path

from .views import (
    TodoCreateView, TodoUpdateView, IndexView, TodoDetailView, TodoJsonView
)


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('todo/<int:pk>/', TodoDetailView.as_view(), name='todo_detail'),
    path('todo/', TodoCreateView.as_view(), name='todo_create'),
    path('todo/<int:pk>/update/', TodoUpdateView.as_view(), name='todo_update'),
    path('todo/json/', TodoJsonView.as_view(), name='todo_json'),
]

todos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/models.py
from django.db import models


class Todo(models.Model):

    title = models.CharField(max_length=255)
    due_date = models.DateField()
    done = models.BooleanField(default=False)
    description = models.TextField()

    def __str__(self):
        return self.title

main/forms.py
from datetime import date

from django import forms

from .models import Todo


class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        fields = '__all__'
        labels = {
            'done': 'Is this task done?',
        }
        help_texts = {
            'due_date': 'Date when task is expected to be done.'
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        words = title.split(' ')
        if len(words) > 5:
            raise forms.ValidationError('The title should be five or less words.')
        return title

    def clean_due_date(self):
        due_date = self.cleaned_data['due_date']
        if due_date < date.today():
            raise forms.ValidationError('The due date cannot be in the past.')
        return due_date

main/views.py
from datetime import datetime

from django.contrib.messages.views import SuccessMessageMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView, UpdateView, ListView, DetailView, View
)

from .forms import TodoForm
from .models import Todo


class IndexView(ListView):

    queryset = Todo.objects.all()
    template_name = 'main/index.html'
    context_object_name = 'todos'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['today'] = datetime.now().date()
        ctx['app_name'] = 'Super Todos'
        return ctx


class TodoDetailView(DetailView):

    model = Todo


class TodoCreateView(SuccessMessageMixin, CreateView):

    model = Todo
    form_class = TodoForm
    success_url = reverse_lazy('index')
    success_message = 'Todo has been created successfully.'


class TodoUpdateView(SuccessMessageMixin, UpdateView):

    model = Todo
    form_class = TodoForm
    success_url = reverse_lazy('index')
    success_message = 'Todo has been updated successfully.'


class TodoJsonView(View):

    http_method_names = ['get', ]

    def get(self, request, *args, **kwargs):
        todos = Todo.objects.filter(done=True).values()
        return JsonResponse({'todos': list(todos)})

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} | The Super Todos{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'main/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/gijgo.min.css' %}">
</head>
<body>

<div class="container">
    <nav class="nav my-5">
        <a class="nav-link" href="{% url 'index' %}">Home</a>
        <a class="nav-link" href="{% url 'todo_create' %}">Create a new todo</a>
    </nav>
    {% include "main/partials/messages.html" %}
    {% block main_content %}{% endblock main_content %}
</div>
<script src="{% static 'main/jquery.min.js' %}" charset="utf-8"></script>
<script src="{% static 'main/gijgo.min.js' %}" charset="utf-8"></script>
<script type="text/javascript">
    $("#id_due_date").datepicker(
        { uiLibrary: 'bootstrap4', iconsLibrary: 'materialicons' }
    );
</script>
</body>
</html>

main/templates/main/index.html
{% extends "main/base.html" %}

{% block title %} Home {{ block.super }}{% endblock title %}

{% block main_content %}
    <p>Today is {{ today }}</p>
    <p>{{ app_name }}</p>

    <h3>Our todos</h3>
    <table class="table table-striped table-dark">
    <thead>
      <tr>
        <th>#</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Done</th>
        <th scope="col">Due date</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for todo in todos %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'todo_update' pk=todo.pk %}">{{ todo.title }}</a></td>
            <td>{{ todo.description|truncatewords:5 }}</td>
            <td>{{ todo.done|yesno:"Yes,No" }}</td>
            <td>{{ todo.due_date }}</td>
            <td><a class="btn btn-info" href="{% url 'todo_detail' pk=todo.pk %}">Show</a></td>
        </tr>
      {% endfor %}
    </tbody>
    </table>
{% endblock main_content %}

main/templates/main/partials/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

main/templates/main/todo_detail.html
{% extends "main/base.html" %}

{% block title %} {{ todo.title }} {{ block.super }}{% endblock title %}
{% block main_content %}
    <div class="card text-center">
        <div class="card-header">
            Due {{ todo.due_date }}
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ todo.title }}</h5>
            <p class="card-text">{{ todo.description }}</p>
        </div>
        <div class="card-footer text-muted">
            {% if not todo.done %}Not {% endif %} Done
        </div>
    </div>
{% endblock main_content %}

main/templates/main/todo_form.html
{% extends "main/base.html" %}

{% load crispy_forms_tags %}
{% block title %}Create a new todo {{ block.super }}{% endblock title %}

{% block main_content %}
    <form class="" action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit" name="button">Save</button>
    </form>
{% endblock main_content %}